brand_slug: b-o-b-bars
brand_name: B.O.B. Bars
platform: shopify
domain: www.usebob.com.br
allowed_domains:
- www.usebob.com.br
entrypoints:
- https://www.usebob.com.br/collections/cabelo
discovery:
  strategy: sitemap_first
  sitemap_urls:
  - https://www.usebob.com.br/collections/cabelo/sitemap.xml
  product_url_pattern: null
  max_pages: 500
  pagination:
    type: scroll
    max_pages: 10
extraction:
  inci_selectors:
  - .product__description p
  - .product-single__description p
  - .product-description p
  name_selectors:
  - h1.product-name
  - h1
  - .product-title
  - .product-name
  image_selectors:
  - .product-image img
  - img.product-img
  - .gallery img
  wait_for_selector: null
  use_llm_fallback: true
version: 1
